name: Typecheck and Deploy App
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck-job:
    name: Run typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
  deploy-job:
    runs-on: ubuntu-latest
    needs: typecheck-job
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master 
        with: 
          host: ${{ secrets.DIGITALOCEAN_HOST }} 
          username: ${{ secrets.DIGITALOCEAN_USERNAME }} 
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }} 
          script: |
            cd kanban-task-management-web-app
            git fetch
            pm2 stop npm
            git checkout origin/main
            git checkout -B main
            rm -r node_modules
            rm -r build
            npm install
            npm run build
            pm2 start npm -- start
